### PR TITLE
Arc

### PR DESCRIPTION
**Pull request by gnzzz**
The ARC part seems to work and this also adds preference panels for os x.

The only concern is in GraphElementProperty.m where a release is uncommented that seems to create a memory leak. This is probably due to the conversion of GC to ARC not being the best, and something that should be looked in to. It does however seem to work fine as is.

### CODE REVIEW

**Comment by gnzzz** [comment]
Thinking about this some more, I think the reason was that the common code elements are non-ARC because the linux version wasn't compiled with ARC. I don't remember if that was because ARC didn't exist for linux or if we just didn't bother migrating it. It should probably be done though since we're forced to ARC on OS X now. In the interim period, perhaps this works and since I don't have any computer with linux on it then I can't do much about it.

**Comment by akissinger** [comment]
Apparently ARC is a clang feature, so it does (in theory) exist in linux. In the mean time, we could wrap retain/release calls in ifndefs to check that ARC is not turned on, then enable ARC in xcode.

**Comment by gnzzz** [comment]
That might be worth it, if we do a check with `__has_feature(objc_arc)` then we can probably do transitional code. It strikes me as a super bad idea though, but it might be the best option at the moment. How about if I try and see if I can get it to work with that and you can see if it compiles nicely on linux?

**Comment by akissinger** [comment]
yeah, i can do that. btw, virtualbox is a godsend for this kind of stuff

**Comment by gnzzz** [comment]
Any good ideas of what to do with the Flex/Bison files? There is a struct in there which isn't allowed in ARC but using the trick I did for the other structs doesn't seem to work. I'm considering changing them to obj-c classes instead but not sure if that would work or if that will mess with the Linux version.

**Comment by gnzzz** [comment]
No luck on classes and all tricks I tried ended up in memory crashes which are probably related to the unsafe use of untracked unsafe variables in ARC. I ended up reverting the relevant three files to be compiled without ARC and it now compiles, runs and most of the time the preview works but the latter I think is related to something on my system. Would you mind trying this on linux?

**Pull request closed without merging**
