### PR TITLE
Nix build

### PR DESCRIPTION
**Pull request by mgttlinger**
I wrote a build using the nix package manager. Maybe this is usefull for some other folks uing nix.
In the next step I want to push this to the nixpkgs repository so that the program becomes available on NixOS.

### CODE REVIEW

**Comment by iblech** [comment]
Hey Merlin! I also wrote a Nix build, see [here](https://github.com/tikzit/tikzit/issues/26). It's already [submitted](https://github.com/NixOS/nixpkgs/pull/48479) to nixpkgs.

Maybe we can merge our efforts?

I'm sorry that our miscommunication resulted in duplicate work for you.

**Comment by mgttlinger** [comment]
Oh... when I started work on this yesterday and searched nixpkgs there was nothing yet. Guess I should have opened an issue.

**Comment by mgttlinger** [comment]
@iblech How should we continue from here?

**Comment by iblech** [comment]
Yeah, I opened an issue here, but it was closed after there was nothing to discuss, so that was no exactly beneficial to visibility.

Do you think that we should go forward before the final version 2.0 is released? If not, we probably have a couple of days. My nix file contains this hack with not using the standard `installPhase` at all; your solution of the problem is much better. On the other hand, I distributed the dependencies between `buildInputs` and `nativeBuildInputs` (hopefully in the proper manner, I don't yet have much experience in creating Nix builds). I'll give you commit access to my branch (the branch associated to the pull request at nixpkgs); if you like this mode of collaborating, feel free to perform any changes you envision.

**Comment by akissinger** [comment]
In any case, I think this file belongs in the nix-pkgs repo and not the tikzit repo. Thanks to both of your for your work. Once this is merged, I'm happy to add (or link) instructions for NixOS users on the website.

**Pull request closed without merging**
